language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 2.7
  - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head
sudo: false
cache: bundler
before_install: gem install bundler
script:
- mkdir log
- bundle exec rake bundle:audit
- bundle exec rubocop
- bundle exec rspec
